image: Visual Studio 2017
artifacts:
  - path: '**\jsreport.Types*.nupkg'
    name: nuget
    type: NuGetPackage
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
  project: jsreport.Types.sln
before_build:
  - cmd: dotnet restore
deploy:
  provider: NuGet
  api_key:
    secure: UBzmpRijxTKAK3TFp80YO5xzaWUaHE4zM3ORRCa0vjqZFEOh6FYwSeANnj0q4TVe
  on:
    appveyor_repo_tag: true

oy2iz633iu3pbseskxkatxieu5h4pxvepbie5m46vjcrmi